title: Khai Nguyen
description: Software Engineer
url: https://khai.work

show_downloads: false

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

include: ["_pages"]
author:
  github: khaister

plugins:
