title: Khai Nguyen
description: Software Developer
google_analytics:
show_downloads: false
#theme: minima
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

twitter:
  username: khaister
author:
  github: khaister

plugins:
